[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
shared = { path = "../../shared" }
risc0-zkvm = { version = "^3.0.1", default-features = false, features = [
    'std',
] }
